### ISSUE TITLE
调试好环境运行train.py报了个CUDA错误，请问该怎么解决呀？

### ISSUE THREAD

**Issue by lh5533223** [tangg555/SaBART#2]
Traceback (most recent call last):
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\pytorch_lightning\trainer\call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 624, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1061, in _run
    results = self._run_stage()
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1140, in _run_stage
    self._run_train()
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1153, in _run_train
    self._run_sanity_check()
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1225, in _run_sanity_check
    val_loop.run()
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\pytorch_lightning\loops\loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\pytorch_lightning\loops\loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1443, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 390, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "E:\lh\SaBART-master\src\models\chabot\bart.py", line 176, in validation_step
    return self._generative_step(batch)
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\lh\SaBART-master\src\models\chabot\chatbot_onehop_model_eh.py", line 193, in _generative_step
    generated_ids = self.model.generate(
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\transformers\generation_utils.py", line 1360, in generate
    return self.beam_search(
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\transformers\generation_utils.py", line 2208, in beam_search
    outputs = self(
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\lh\SaBART-master\src\models\chabot\chatbot_onehop_model_eh.py", line 70, in forward
    graph_batch.ndata['h'] = self.get_input_embeddings()(graph_batch.ndata['h']).view(-1, self.config.hidden_size * 4)
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\torch\nn\modules\sparse.py", line 158, in forward
    return F.embedding(
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\torch\nn\functional.py", line 2183, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: CUDA error: device-side assert triggered

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/lh/SaBART-master/tasks/chatbot/train.py", line 112, in <module>
    trainer.train()
  File "E:/lh/SaBART-master/tasks/chatbot/train.py", line 106, in train
    self.pl_trainer.fit(self.model)
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 582, in fit
    call._call_and_handle_interrupt(
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\pytorch_lightning\trainer\call.py", line 63, in _call_and_handle_interrupt
    trainer._teardown()
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1124, in _teardown
    self.strategy.teardown()
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 496, in teardown
    self.lightning_module.cpu()
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\lightning_lite\utilities\device_dtype_mixin.py", line 78, in cpu
    return super().cpu()
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\torch\nn\modules\module.py", line 718, in cpu
    return self._apply(lambda t: t.cpu())
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\torch\nn\modules\module.py", line 578, in _apply
    module._apply(fn)
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\torch\nn\modules\module.py", line 578, in _apply
    module._apply(fn)
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\torch\nn\modules\module.py", line 578, in _apply
    module._apply(fn)
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\torch\nn\modules\module.py", line 601, in _apply
    param_applied = fn(param)
  File "E:\software\anaconda\install\envs\SaBART\lib\site-packages\torch\nn\modules\module.py", line 718, in <lambda>
    return self._apply(lambda t: t.cpu())
RuntimeError: CUDA error: device-side assert triggered

**Comment by lh5533223** [comment]
已经设置CUDA_LAUNCH_BLOCKING=1
![image](https://github.com/user-attachments/assets/1c424292-2331-45a1-a8b0-d36d6d5ab255)

**Comment by tangg555** [comment]
你好，看了一下错误类型，这种错误类型大概率是各个包的版本匹配问题。建议可以debug到具体是哪个语句报了这个错误来定位一下。
